import {
  MAP_01_ID,
  MAP_01_NAME,
  MAP_01_SIZE_M,
} from '@/maps/map-01-blockout/constants.ts'
import type { Map01BlockoutData } from '@/maps/map-01-blockout/types.ts'
import { defaultMap01TerrainData } from '@/maps/map-01-blockout/terrainHeight.ts'

const now = () => new Date().toISOString()

/**
 * Produkční blockout Map 01 — Varianta A „Návrší a údolí".
 * Souřadnice a logika odvozeny z Master Plan, Field Layout, Road Network.
 */
export function createMap01BlockoutData(): Map01BlockoutData {
  return {
    metadata: {
      id: MAP_01_ID,
      name: MAP_01_NAME,
      description:
        'Produkční blockout — středoevropská kotlinová krajina, farma na návrší, údolí řeky, vesnice na hřebeni.',
      variant: 'A',
      sizeMeters: { width: MAP_01_SIZE_M, depth: MAP_01_SIZE_M },
      sourceDocuments: [
        'Map_01_Master_Plan.md',
        'Map_01_Spatial_Design.md',
        'Map_01_Landscape_Layout.md',
        'Map_01_Agricultural_Master_Plan.md',
        'Map_01_Road_Network.md',
        'Map_01_Field_Layout.md',
        'Map_01_View_Composition.md',
      ],
      author: 'FarmOS World Director',
      createdAt: now(),
    },
    terrain: defaultMap01TerrainData(),
    fields: [
      {
        id: 'field_1',
        name: 'Domácí pole',
        parcelId: 'A-01',
        parcelBlock: 'A',
        center: { x: -90, z: -1040 },
        size: { width: 240, depth: 190 },
        fertility: 85,
        roadAccess: 'farm_road',
        kind: 'field',
      },
      {
        id: 'field_2',
        name: 'U rybníka',
        parcelId: 'A-02',
        parcelBlock: 'A',
        center: { x: 310, z: -990 },
        size: { width: 200, depth: 170 },
        fertility: 80,
        roadAccess: 'service_pond',
        kind: 'field',
      },
      {
        id: 'field_3',
        name: 'Přední svah',
        parcelId: 'A-03',
        parcelBlock: 'A',
        center: { x: 80, z: -820 },
        size: { width: 280, depth: 220 },
        rotationY: 0.08,
        fertility: 82,
        roadAccess: 'field_access_a',
        kind: 'field',
      },
      {
        id: 'field_4',
        name: 'Východní lán',
        parcelId: 'A-04',
        parcelBlock: 'A',
        center: { x: 420, z: -1120 },
        size: { width: 200, depth: 180 },
        fertility: 78,
        roadAccess: 'farm_road',
        kind: 'field',
      },
      {
        id: 'field_5',
        name: 'B-01 Horní lán',
        parcelId: 'B-01',
        parcelBlock: 'B',
        center: { x: -40, z: -180 },
        size: { width: 520, depth: 480 },
        fertility: 82,
        roadAccess: 'field_access_b',
        kind: 'field',
      },
      {
        id: 'field_6',
        name: 'B-01 Dolní lán',
        parcelId: 'B-01b',
        parcelBlock: 'B',
        center: { x: 120, z: 80 },
        size: { width: 480, depth: 400 },
        fertility: 88,
        roadAccess: 'field_access_b',
        kind: 'field',
      },
      {
        id: 'field_7',
        name: 'B-02 Údolní pole',
        parcelId: 'B-02',
        parcelBlock: 'B',
        center: { x: -220, z: 360 },
        size: { width: 520, depth: 380 },
        fertility: 80,
        roadAccess: 'field_access_b',
        kind: 'field',
      },
      {
        id: 'field_8',
        name: 'B-03 U cesty',
        parcelId: 'B-03',
        parcelBlock: 'B',
        center: { x: 480, z: 80 },
        size: { width: 420, depth: 460 },
        fertility: 76,
        roadAccess: 'field_access_b',
        kind: 'field',
      },
      {
        id: 'field_9',
        name: 'C-01 Přes údolí',
        parcelId: 'C-01',
        parcelBlock: 'C',
        center: { x: 120, z: 1180 },
        size: { width: 380, depth: 320 },
        rotationY: -0.12,
        fertility: 84,
        roadAccess: 'field_access_c',
        kind: 'field',
      },
      {
        id: 'meadow_m01',
        name: 'Nivní louka',
        parcelId: 'M-01',
        parcelBlock: 'M',
        center: { x: -350, z: 420 },
        size: { width: 480, depth: 160 },
        fertility: 0,
        kind: 'meadow',
      },
      {
        id: 'meadow_m02',
        name: 'Přechodová louka',
        parcelId: 'M-02',
        parcelBlock: 'M',
        center: { x: 60, z: -520 },
        size: { width: 320, depth: 140 },
        fertility: 0,
        kind: 'meadow',
      },
      {
        id: 'meadow_m03',
        name: 'Louka u potoka',
        parcelId: 'M-03',
        parcelBlock: 'M',
        center: { x: 420, z: -880 },
        size: { width: 200, depth: 120 },
        fertility: 0,
        kind: 'meadow',
      },
    ],
    roads: [
      {
        id: 'road_primary_farm_village',
        name: 'Primary — farma → most → vesnice',
        roadKind: 'asphalt_wide',
        category: 'primary',
        points: [
          { x: 0, z: -920 },
          { x: 0, z: -400 },
          { x: 0, z: 120 },
          { x: 0, z: 460 },
          { x: 40, z: 820 },
          { x: 120, z: 1320 },
          { x: 140, z: 1520 },
        ],
      },
      {
        id: 'road_secondary_samota',
        name: 'Secondary — odbočka k samotě',
        roadKind: 'asphalt_narrow',
        category: 'secondary',
        points: [
          { x: 0, z: 460 },
          { x: -420, z: 620 },
          { x: -780, z: 740 },
        ],
      },
      {
        id: 'road_farm_yard',
        name: 'Farm road — dvůr',
        roadKind: 'field_path',
        category: 'farm',
        points: [
          { x: -60, z: -1080 },
          { x: 0, z: -1040 },
          { x: 80, z: -1020 },
          { x: 120, z: -980 },
        ],
      },
      {
        id: 'road_field_access_a',
        name: 'Field access — Block A',
        roadKind: 'field_path',
        category: 'field_access',
        points: [
          { x: 0, z: -1020 },
          { x: -90, z: -1040 },
          { x: 80, z: -820 },
          { x: 100, z: -680 },
        ],
      },
      {
        id: 'road_field_access_b',
        name: 'Field access — Block B (údolí)',
        roadKind: 'field_path',
        category: 'field_access',
        points: [
          { x: 0, z: 120 },
          { x: -40, z: -180 },
          { x: -220, z: 360 },
          { x: 200, z: 520 },
          { x: 480, z: 80 },
        ],
      },
      {
        id: 'road_field_access_c',
        name: 'Field access — Block C (za mostem)',
        roadKind: 'field_path',
        category: 'field_access',
        points: [
          { x: 0, z: 460 },
          { x: 120, z: 1180 },
          { x: -280, z: 1050 },
        ],
      },
      {
        id: 'road_forest_west',
        name: 'Forest road — západní pás',
        roadKind: 'field_path',
        category: 'forest',
        points: [
          { x: -200, z: 460 },
          { x: -900, z: 800 },
          { x: -1400, z: 1100 },
        ],
      },
      {
        id: 'road_service_pond',
        name: 'Service track — rybník',
        roadKind: 'field_path',
        category: 'service',
        points: [
          { x: 80, z: -1020 },
          { x: 280, z: -1020 },
        ],
      },
      {
        id: 'road_scenic_ridge',
        name: 'Scenic route — severní hřeben',
        roadKind: 'field_path',
        category: 'scenic',
        points: [
          { x: 120, z: 1320 },
          { x: 600, z: 1500 },
          { x: 1100, z: 1680 },
          { x: 1600, z: 1780 },
        ],
      },
    ],
    buildings: [
      {
        id: 'building_farm_barn',
        name: 'Hlavní stodola',
        buildingType: 'farm_barn',
        position: { x: -40, z: -1100 },
      },
      {
        id: 'building_farm_mill',
        name: 'Mlýn statku',
        buildingType: 'farm_mill',
        position: { x: -140, z: -1060 },
        rotationY: 0.4,
      },
      {
        id: 'building_farm_silo',
        name: 'Silo',
        buildingType: 'farm_silo',
        position: { x: 60, z: -1140 },
      },
      {
        id: 'building_farm_house',
        name: 'Statkářský dům',
        buildingType: 'house_family_farm',
        position: { x: -120, z: -1140 },
        rotationY: -0.2,
      },
      {
        id: 'building_dealership',
        name: 'Obchod se stroji',
        buildingType: 'shop_general',
        position: { x: 200, z: -940 },
        rotationY: 1.2,
      },
      {
        id: 'building_village_church',
        name: 'Kostel',
        buildingType: 'civic_church',
        position: { x: 100, z: 1580 },
        rotationY: 0,
      },
      {
        id: 'building_village_inn',
        name: 'Hospoda',
        buildingType: 'shop_general',
        position: { x: 220, z: 1500 },
        rotationY: -0.5,
      },
      {
        id: 'building_village_house_1',
        name: 'Dům náves 1',
        buildingType: 'house_family_standard',
        position: { x: -80, z: 1480 },
      },
      {
        id: 'building_village_house_2',
        name: 'Dům náves 2',
        buildingType: 'house_family_standard',
        position: { x: 40, z: 1460 },
        rotationY: 0.3,
      },
      {
        id: 'building_village_house_3',
        name: 'Dům náves 3',
        buildingType: 'house_family_small',
        position: { x: 180, z: 1440 },
      },
      {
        id: 'building_village_house_4',
        name: 'Dům náves 4',
        buildingType: 'house_family_large',
        position: { x: -200, z: 1520 },
        rotationY: -0.4,
      },
      {
        id: 'building_homestead_samota',
        name: 'Samota',
        buildingType: 'house_family_farm',
        position: { x: -820, z: 780 },
        rotationY: 0.8,
      },
      {
        id: 'building_shed_valley',
        name: 'Seník u údolí',
        buildingType: 'farm_shed',
        position: { x: -500, z: 500 },
      },
    ],
    water: [
      {
        id: 'water_river_main',
        name: 'Hlavní řeka',
        waterType: 'water_river_medium',
        placementKind: 'spline',
        points: [
          { x: -1600, z: 280 },
          { x: -800, z: 320 },
          { x: -200, z: 340 },
          { x: 400, z: 300 },
          { x: 1200, z: 360 },
          { x: 1800, z: 400 },
        ],
      },
      {
        id: 'water_pond_farm',
        name: 'Rybník u farmy',
        waterType: 'water_pond_large',
        placementKind: 'area',
        center: { x: 300, z: -1020 },
        radiusX: 95,
        radiusZ: 70,
      },
      {
        id: 'water_stream_feeder',
        name: 'Potok k rybníku',
        waterType: 'water_stream_small',
        placementKind: 'spline',
        points: [
          { x: 420, z: -880 },
          { x: 360, z: -940 },
          { x: 300, z: -1020 },
        ],
      },
      {
        id: 'water_wetland_niva',
        name: 'Mokřad v nivě',
        waterType: 'water_pool',
        placementKind: 'area',
        center: { x: -420, z: 480 },
        radiusX: 120,
        radiusZ: 60,
      },
    ],
    vegetation: [
      {
        id: 'forest_north_ridge',
        name: 'Les — severní hřeben',
        vegetationType: 'tree_tall_wide',
        bounds: { minX: -1700, maxX: 1700, minZ: 1650, maxZ: 1950 },
        densityPerSqM: 0.00012,
        seed: 11,
        category: 'forest',
      },
      {
        id: 'forest_west_slope',
        name: 'Les — západní svah',
        vegetationType: 'tree_tall_narrow',
        bounds: { minX: -1950, maxX: -1200, minZ: -400, maxZ: 1400 },
        densityPerSqM: 0.0001,
        seed: 23,
        category: 'forest',
      },
      {
        id: 'forest_east_edge',
        name: 'Les — východní okraj',
        vegetationType: 'tree_medium_wide',
        bounds: { minX: 1200, maxX: 1950, minZ: 200, maxZ: 1600 },
        densityPerSqM: 0.00009,
        seed: 37,
        category: 'forest',
      },
      {
        id: 'hedgerow_a_b',
        name: 'Remízek A–B',
        vegetationType: 'shrub_medium_wide',
        bounds: { minX: -40, maxX: 200, minZ: -620, maxZ: -480 },
        densityPerSqM: 0.00035,
        seed: 41,
        category: 'hedgerow',
      },
      {
        id: 'hedgerow_b_river',
        name: 'Remízek B–řeka',
        vegetationType: 'shrub_low_wide',
        bounds: { minX: -500, maxX: 100, minZ: 280, maxZ: 420 },
        densityPerSqM: 0.0003,
        seed: 43,
        category: 'hedgerow',
      },
      {
        id: 'alley_primary',
        name: 'Alej podél primary',
        vegetationType: 'tree_medium_narrow',
        bounds: { minX: -30, maxX: 30, minZ: -800, maxZ: 1400 },
        densityPerSqM: 0.0005,
        seed: 51,
        category: 'alley',
      },
      {
        id: 'solitary_farm',
        name: 'Solitérní stromy u farmy',
        vegetationType: 'tree_tall_narrow',
        bounds: { minX: -300, maxX: 400, minZ: -1250, maxZ: -900 },
        densityPerSqM: 0.00004,
        seed: 61,
        category: 'solitary',
      },
      {
        id: 'conifer_patch_east',
        name: 'Jehličnatý pás',
        vegetationType: 'tree_tall_narrow',
        bounds: { minX: 900, maxX: 1300, minZ: 900, maxZ: 1300 },
        densityPerSqM: 0.00014,
        seed: 71,
        category: 'forest',
      },
    ],
    poi: [
      {
        id: 'poi_tractor_spawn',
        name: 'Tractor Home',
        kind: 'spawn',
        position: { x: 0, z: -1040 },
        properties: { entity: 'tractor' },
      },
      {
        id: 'poi_hero_view_farm',
        name: 'Hero View — CM-01',
        kind: 'camera_moment',
        position: { x: 0, z: -1120 },
        properties: { viewId: 'CM-01', label: 'Moje farma' },
      },
      {
        id: 'poi_hero_view_panorama',
        name: 'Hero View — CM-02',
        kind: 'camera_moment',
        position: { x: 0, z: -1080 },
        properties: { viewId: 'CM-02', label: 'Panorama' },
      },
      {
        id: 'poi_bridge',
        name: 'Most přes řeku',
        kind: 'landmark',
        position: { x: 0, z: 460 },
      },
    ],
  }
}
