import { VEGETATION_LOD_DEFAULTS, VEGETATION_LAYER_LOD_OVERRIDES } from './vegetation-lod-config.ts'
import { VEGETATION_WIND_CONFIG } from './vegetation-wind-config.ts'
import type { VegetationLayerDefinition } from '@/types/vegetation-rendering.ts'

const grassWind = {
  enabled: VEGETATION_WIND_CONFIG.enabled,
  strength: VEGETATION_WIND_CONFIG.grassStrength,
  frequency: VEGETATION_WIND_CONFIG.baseFrequency,
  swayAxis: 'x' as const,
}

const shrubWind = {
  enabled: VEGETATION_WIND_CONFIG.enabled,
  strength: VEGETATION_WIND_CONFIG.shrubStrength,
  frequency: VEGETATION_WIND_CONFIG.gustFrequency,
  swayAxis: 'z' as const,
}

const treeWind = {
  enabled: VEGETATION_WIND_CONFIG.enabled,
  strength: VEGETATION_WIND_CONFIG.treeStrength,
  frequency: VEGETATION_WIND_CONFIG.gustFrequency,
  swayAxis: 'x' as const,
}

export const VEGETATION_LAYER_CATALOG: readonly VegetationLayerDefinition[] = [
  {
    id: 'short_grass',
    displayName: 'Short Grass',
    type: 'short_grass',
    enabled: true,
    density: 0.82,
    minScale: 0.75,
    maxScale: 1.15,
    scatterSpacing: 1.15,
    colorVariation: { hueShift: 0.04, saturationShift: 0.06, brightnessShift: 0.05 },
    heightVariation: { min: 0.08, max: 0.16 },
    placementRules: [
      { id: 'avoid_roads', weight: 1 },
      { id: 'avoid_field_centers', weight: 1 },
      { id: 'meadow_bias', weight: 0.7 },
    ],
    lod: { ...VEGETATION_LOD_DEFAULTS, ...VEGETATION_LAYER_LOD_OVERRIDES.short_grass },
    windProfile: grassWind,
    materialProfile: {
      placeholderAssetId: 'placeholder_short_grass',
      receiveShadows: true,
      castShadows: false,
    },
    debugColor: [0.3, 0.8, 0.3],
    maxInstances: 12000,
  },
  {
    id: 'meadow_grass',
    displayName: 'Meadow Grass',
    type: 'meadow_grass',
    enabled: true,
    density: 0.55,
    minScale: 0.85,
    maxScale: 1.35,
    scatterSpacing: 1.8,
    colorVariation: { hueShift: 0.05, saturationShift: 0.05, brightnessShift: 0.04 },
    heightVariation: { min: 0.22, max: 0.42 },
    placementRules: [
      { id: 'meadow_bias', weight: 1 },
      { id: 'avoid_roads', weight: 0.8 },
      { id: 'avoid_field_centers', weight: 0.9 },
    ],
    lod: VEGETATION_LOD_DEFAULTS,
    windProfile: grassWind,
    materialProfile: {
      placeholderAssetId: 'placeholder_meadow_grass',
      receiveShadows: true,
      castShadows: false,
    },
    debugColor: [0.2, 0.7, 0.35],
    maxInstances: 6000,
  },
  {
    id: 'field_margin',
    displayName: 'Field Margin',
    type: 'field_margin',
    enabled: true,
    density: 0.72,
    minScale: 0.8,
    maxScale: 1.2,
    scatterSpacing: 1.4,
    colorVariation: { hueShift: 0.03, saturationShift: 0.04, brightnessShift: 0.03 },
    heightVariation: { min: 0.18, max: 0.34 },
    placementRules: [{ id: 'field_edge_boost', weight: 1 }],
    lod: VEGETATION_LOD_DEFAULTS,
    windProfile: grassWind,
    materialProfile: {
      placeholderAssetId: 'placeholder_dry_grass',
      receiveShadows: true,
      castShadows: false,
    },
    debugColor: [0.75, 0.7, 0.25],
    maxInstances: 3500,
  },
  {
    id: 'roadside_grass',
    displayName: 'Roadside Grass',
    type: 'roadside_grass',
    enabled: true,
    density: 0.68,
    minScale: 0.8,
    maxScale: 1.15,
    scatterSpacing: 1.35,
    colorVariation: { hueShift: 0.03, saturationShift: 0.03, brightnessShift: 0.02 },
    heightVariation: { min: 0.12, max: 0.24 },
    placementRules: [{ id: 'road_edge_boost', weight: 1 }],
    lod: VEGETATION_LOD_DEFAULTS,
    windProfile: grassWind,
    materialProfile: {
      placeholderAssetId: 'placeholder_short_grass',
      receiveShadows: true,
      castShadows: false,
    },
    debugColor: [0.45, 0.75, 0.3],
    maxInstances: 2800,
  },
  {
    id: 'shrub',
    displayName: 'Shrub',
    type: 'shrub',
    enabled: true,
    density: 0.42,
    minScale: 0.85,
    maxScale: 1.25,
    scatterSpacing: 3.2,
    colorVariation: { hueShift: 0.04, saturationShift: 0.05, brightnessShift: 0.03 },
    heightVariation: { min: 0.9, max: 1.8 },
    placementRules: [
      { id: 'field_edge_boost', weight: 0.8 },
      { id: 'forest_edge_boost', weight: 0.6 },
    ],
    lod: VEGETATION_LOD_DEFAULTS,
    windProfile: shrubWind,
    materialProfile: {
      placeholderAssetId: 'placeholder_shrub_small',
      receiveShadows: true,
      castShadows: true,
    },
    debugColor: [0.15, 0.55, 0.15],
    maxInstances: 1200,
  },
  {
    id: 'hedgerow',
    displayName: 'Hedgerow',
    type: 'hedgerow',
    enabled: true,
    density: 0.58,
    minScale: 0.9,
    maxScale: 1.2,
    scatterSpacing: 2.4,
    colorVariation: { hueShift: 0.03, saturationShift: 0.04, brightnessShift: 0.02 },
    heightVariation: { min: 1.1, max: 2.2 },
    placementRules: [{ id: 'hedgerow_lines', weight: 1 }],
    lod: VEGETATION_LOD_DEFAULTS,
    windProfile: shrubWind,
    materialProfile: {
      placeholderAssetId: 'placeholder_shrub_large',
      receiveShadows: true,
      castShadows: true,
    },
    debugColor: [0.12, 0.5, 0.14],
    maxInstances: 900,
  },
  {
    id: 'forest_edge',
    displayName: 'Forest Edge',
    type: 'forest_edge',
    enabled: true,
    density: 0.5,
    minScale: 0.9,
    maxScale: 1.35,
    scatterSpacing: 2.8,
    colorVariation: { hueShift: 0.03, saturationShift: 0.04, brightnessShift: 0.02 },
    heightVariation: { min: 1.4, max: 2.8 },
    placementRules: [{ id: 'forest_edge_boost', weight: 1 }],
    lod: VEGETATION_LOD_DEFAULTS,
    windProfile: shrubWind,
    materialProfile: {
      placeholderAssetId: 'placeholder_forest_edge',
      receiveShadows: true,
      castShadows: true,
    },
    debugColor: [0.1, 0.42, 0.12],
    maxInstances: 1400,
  },
  {
    id: 'tree_line',
    displayName: 'Tree Line',
    type: 'tree_line',
    enabled: true,
    density: 0.48,
    minScale: 0.95,
    maxScale: 1.2,
    scatterSpacing: 6.5,
    colorVariation: { hueShift: 0.02, saturationShift: 0.03, brightnessShift: 0.02 },
    heightVariation: { min: 4.5, max: 7.5 },
    placementRules: [{ id: 'tree_line_alley', weight: 1 }],
    lod: { ...VEGETATION_LOD_DEFAULTS, ...VEGETATION_LAYER_LOD_OVERRIDES.tree_line },
    windProfile: treeWind,
    materialProfile: {
      placeholderAssetId: 'placeholder_young_tree',
      receiveShadows: true,
      castShadows: true,
    },
    debugColor: [0.08, 0.38, 0.1],
    maxInstances: 320,
  },
  {
    id: 'scattered_tree',
    displayName: 'Scattered Tree',
    type: 'scattered_tree',
    enabled: true,
    density: 0.35,
    minScale: 0.9,
    maxScale: 1.3,
    scatterSpacing: 9.5,
    colorVariation: { hueShift: 0.02, saturationShift: 0.03, brightnessShift: 0.02 },
    heightVariation: { min: 5, max: 9 },
    placementRules: [
      { id: 'forest_interior_boost', weight: 0.7 },
      { id: 'avoid_roads', weight: 1 },
      { id: 'avoid_field_centers', weight: 1 },
    ],
    lod: { ...VEGETATION_LOD_DEFAULTS, ...VEGETATION_LAYER_LOD_OVERRIDES.scattered_tree },
    windProfile: treeWind,
    materialProfile: {
      placeholderAssetId: 'placeholder_young_tree',
      receiveShadows: true,
      castShadows: true,
    },
    debugColor: [0.06, 0.34, 0.08],
    maxInstances: 500,
  },
] as const

export function getVegetationLayerDefinition(
  layerId: VegetationLayerDefinition['id'],
): VegetationLayerDefinition {
  return (
    VEGETATION_LAYER_CATALOG.find((layer) => layer.id === layerId) ??
    VEGETATION_LAYER_CATALOG[0]
  )
}
